trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  LAMBDATEST_USERNAME: 'rahulkumarlambdatest'
  LAMBDATEST_ACCESS_KEY: 'dboZK7so8koMnIR1tN11aKfMgxyKtDpb90IlyaCj4n6n7tQeK6'

stages:
- stage: UploadAndTriggerTest
  jobs:
  - job: UploadAndRunTests
    steps:

    - script: |
        curl --location --request POST 'https://mobile-api.lambdatest.com/framework/v1/xcui/build' \
        --header "Authorization: Basic YW1pcmFuZGFoZWFsdGhjYXJlYmx1ZWJvb2s6U1hTb0tBVENHelpWd1p0THJWaERuTjFXbzN1cnl3RjR3bjN2aUtxZjRZMjNPajhiWXE=" \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "app" : "lt://APP10160571441724765428716240",
          "testSuite": "lt://APP10160571441724676729189480",
          "device" :  ["iPhone 11-14"],
          "video" : true,
          "queueTimeout": 10800,
          "idleTimeout": 150,
          "devicelog": true,
          "network": false,
          "build" : "Proverbial-XCUITest"
        }'
      displayName: 'Trigger XCUI Test on LambdaTest'
      continueOnError: false
