trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  LAMBDATEST_USERNAME: 'rahulkumarlambdatest'
  LAMBDATEST_ACCESS_KEY: 'dboZK7so8koMnIR1tN11aKfMgxyKtDpb90IlyaCj4n6n7tQeK6'
  APP_PATH: 'ArchivedBluebook3ipa-1723586264662.ipa'
  TEST_SUITE_PATH: 'Payloadipa-1723586910754.ipa'

stages:
- stage: UploadAndTriggerTest
  jobs:
  - job: UploadAndRunTests
    steps:

    - script: |
        APP_UPLOAD_RESPONSE=$(curl --http1.1 -u "$(LAMBDATEST_USERNAME):$(LAMBDATEST_ACCESS_KEY)" --location --request POST 'https://manual-api.lambdatest.com/app/uploadFramework' --form "appFile=@\"$(APP_PATH)\"" --form 'type="xcuit-ios"')
        APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r '.app_id')
        echo "##vso[task.setvariable variable=APP_ID]$APP_ID"
        echo "Suite ID: $(APP_ID)"
      name: Upload_iOS_App
      displayName: 'Upload iOS App to LambdaTest'
      continueOnError: false

    - script: |
        TEST_SUITE_UPLOAD_RESPONSE=$(curl --http1.1 -u "$(LAMBDATEST_USERNAME):$(LAMBDATEST_ACCESS_KEY)" --location --request POST 'https://manual-api.lambdatest.com/app/uploadFramework' --form "appFile=@\"$(TEST_SUITE_PATH)\"" --form 'type="xcuit-ios"')
        TEST_SUITE_ID=$(echo $TEST_SUITE_UPLOAD_RESPONSE | jq -r '.app_id')
        echo "##vso[task.setvariable variable=TEST_SUITE_ID]$TEST_SUITE_ID"
        echo "Test Suite ID: $(TEST_SUITE_ID)"
      name: Upload_Test_Suite
      displayName: 'Upload Test Suite to LambdaTest'
      continueOnError: false

    - script: |
        curl --http1.1 --location --request POST 'https://mobile-api.lambdatest.com/framework/v1/xcui/build' \
        --header "Authorization: Basic cmFodWxrdW1hcmxhbWJkYXRlc3Q6ZGJvWks3c284a29NbklSMXROMTFhS2ZNZ3h5S3REcGI5MElseWFDajRuNm43dFFlSzY=" \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "app" : "$(APP_ID)",
          "testSuite": "$(TEST_SUITE_ID)",
          "device" :  ["iPhone 15-17"],
          "video" : true,
          "queueTimeout": 10800,
          "idleTimeout": 150,
          "devicelog": true,
          "network": false,
          "build" : ""
        }'
      displayName: 'Trigger XCUI Test on LambdaTest'
      continueOnError: false
